extern crate bindgen;
use std::env;
use std::path::PathBuf;

fn main() {
    println!(r"cargo:rerun-if-changed=wrapper.h");

    let bindings = bindgen::Builder::default()
        .clang_args(&["-I", "../../vendor/sleuthkit"])
        .header("wrapper.h")
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .derive_debug(true)
        .derive_default(true)
        .allowlist_function("tsk_version_get_str")
        .generate()
        .expect("Unable to generate bindings");

    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    bindings
        .write_to_file(out_path.join("bindings.rs"))
        .expect("Couldn't write bindings!");

    let dst = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let build = dst.join("build");

    // Build all C sources. In the submodule, get the list of files with:
    // make --dry-run VERBOSE=1 tsk/libtsk.la | rg -o 'tsk/[^ ]+\.c\b'
    let mut cfg = cc::Build::new();
    cfg.out_dir(&build)
        .include("../../vendor/sleuthkit/tsk")
        .include("../../vendor/sleuthkit")
        .file("../../vendor/sleuthkit/tsk/base/crc.c")
        .file("../../vendor/sleuthkit/tsk/base/md5c.c")
        .file("../../vendor/sleuthkit/tsk/base/mymalloc.c")
        .file("../../vendor/sleuthkit/tsk/base/sha1c.c")
        .file("../../vendor/sleuthkit/tsk/base/tsk_base_i.c")
        .file("../../vendor/sleuthkit/tsk/base/tsk_endian.c")
        .file("../../vendor/sleuthkit/tsk/base/tsk_error.c")
        .file("../../vendor/sleuthkit/tsk/base/tsk_list.c")
        .file("../../vendor/sleuthkit/tsk/base/tsk_lock.c")
        .file("../../vendor/sleuthkit/tsk/base/tsk_parse.c")
        .file("../../vendor/sleuthkit/tsk/base/tsk_printf.c")
        .file("../../vendor/sleuthkit/tsk/base/tsk_stack.c")
        .file("../../vendor/sleuthkit/tsk/base/tsk_unicode.c")
        .file("../../vendor/sleuthkit/tsk/base/tsk_version.c")
        .file("../../vendor/sleuthkit/tsk/base/XGetopt.c")
        .file("../../vendor/sleuthkit/tsk/fs/dcat_lib.c")
        .file("../../vendor/sleuthkit/tsk/fs/exfatfs.c")
        .file("../../vendor/sleuthkit/tsk/fs/fatfs_utils.c")
        .file("../../vendor/sleuthkit/tsk/fs/fatxxfs.c")
        .file("../../vendor/sleuthkit/tsk/fs/fatxxfs_dent.c")
        .file("../../vendor/sleuthkit/tsk/fs/ffind_lib.c")
        .file("../../vendor/sleuthkit/tsk/fs/fls_lib.c")
        .file("../../vendor/sleuthkit/tsk/fs/fs_attrlist.c")
        .file("../../vendor/sleuthkit/tsk/fs/fs_block.c")
        .file("../../vendor/sleuthkit/tsk/fs/fs_inode.c")
        .file("../../vendor/sleuthkit/tsk/fs/fs_io.c")
        .file("../../vendor/sleuthkit/tsk/fs/fs_open.c")
        .file("../../vendor/sleuthkit/tsk/fs/fs_parse.c")
        .file("../../vendor/sleuthkit/tsk/fs/fs_types.c")
        .file("../../vendor/sleuthkit/tsk/fs/lzvn.c")
        .file("../../vendor/sleuthkit/tsk/fs/rawfs.c")
        .file("../../vendor/sleuthkit/tsk/fs/swapfs.c")
        .file("../../vendor/sleuthkit/tsk/hashdb/hashkeeper.c")
        .file("../../vendor/sleuthkit/tsk/img/aff.c")
        .file("../../vendor/sleuthkit/tsk/img/img_types.c")
        .file("../../vendor/sleuthkit/tsk/util/detect_encryption.c")
        .file("../../vendor/sleuthkit/tsk/util/detect_encryption.c")
        .file("../../vendor/sleuthkit/tsk/vs/bsd.c")
        .file("../../vendor/sleuthkit/tsk/vs/dos.c")
        .file("../../vendor/sleuthkit/tsk/vs/gpt.c")
        .file("../../vendor/sleuthkit/tsk/vs/mac.c")
        .file("../../vendor/sleuthkit/tsk/vs/mm_io.c")
        .file("../../vendor/sleuthkit/tsk/vs/mm_open.c")
        .file("../../vendor/sleuthkit/tsk/vs/mm_part.c")
        .file("../../vendor/sleuthkit/tsk/vs/mm_types.c")
        .file("../../vendor/sleuthkit/tsk/vs/sun.c");
    cfg.compile("tsk");

    // Separate build for C++ files, get the list of files with:
    // make --dry-run VERBOSE=1 tsk/libtsk.la | rg -o 'tsk/[^ ]+\.cpp\b'
    let mut cfg_cc = cc::Build::new();
    cfg_cc
        .out_dir(&build)
        .include("../../vendor/sleuthkit/tsk")
        .include("../../vendor/sleuthkit")
        .cpp(true)
        .file("../../vendor/sleuthkit/tsk/auto/auto.cpp")
        .file("../../vendor/sleuthkit/tsk/auto/auto.cpp")
        .file("../../vendor/sleuthkit/tsk/auto/auto_db.cpp")
        .file("../../vendor/sleuthkit/tsk/auto/auto_db.cpp")
        .file("../../vendor/sleuthkit/tsk/auto/case_db.cpp")
        .file("../../vendor/sleuthkit/tsk/auto/case_db.cpp")
        .file("../../vendor/sleuthkit/tsk/auto/db_sqlite.cpp")
        .file("../../vendor/sleuthkit/tsk/auto/db_sqlite.cpp")
        .file("../../vendor/sleuthkit/tsk/auto/guid.cpp")
        .file("../../vendor/sleuthkit/tsk/auto/guid.cpp")
        .file("../../vendor/sleuthkit/tsk/auto/is_image_supported.cpp")
        .file("../../vendor/sleuthkit/tsk/auto/is_image_supported.cpp")
        .file("../../vendor/sleuthkit/tsk/auto/tsk_db.cpp")
        .file("../../vendor/sleuthkit/tsk/auto/tsk_db.cpp")
        .file("../../vendor/sleuthkit/tsk/base/tsk_error_win32.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/apfs_compat.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/apfs.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/apfs_fs.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/apfs_open.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/dcalc_lib.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/decmpfs.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/dls_lib.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/dstat_lib.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/encryptionHelper.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/exfatfs_dent.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/exfatfs_meta.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/ext2fs.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/ext2fs_dent.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/ext2fs_journal.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/fatfs.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/fatfs_dent.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/fatfs_meta.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/fatxxfs_meta.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/ffs.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/ffs_dent.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/fs_attr.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/fs_dir.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/fs_file.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/fs_load.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/fs_name.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/hfs.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/hfs_dent.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/hfs_journal.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/hfs_unicompare.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/icat_lib.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/ifind_lib.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/ils_lib.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/iso9660.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/iso9660_dent.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/logical_fs.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/nofs_misc.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/ntfs.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/ntfs_dent.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/unix_misc.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/usnjls_lib.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/usn_journal.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/walk_cpp.cpp")
        .file("../../vendor/sleuthkit/tsk/fs/yaffs.cpp")
        .file("../../vendor/sleuthkit/tsk/hashdb/binsrch_index.cpp")
        .file("../../vendor/sleuthkit/tsk/hashdb/encase.cpp")
        .file("../../vendor/sleuthkit/tsk/hashdb/hdb_base.cpp")
        .file("../../vendor/sleuthkit/tsk/hashdb/idxonly.cpp")
        .file("../../vendor/sleuthkit/tsk/hashdb/md5sum.cpp")
        .file("../../vendor/sleuthkit/tsk/hashdb/nsrl.cpp")
        .file("../../vendor/sleuthkit/tsk/hashdb/sqlite_hdb.cpp")
        .file("../../vendor/sleuthkit/tsk/hashdb/tsk_hashdb.cpp")
        .file("../../vendor/sleuthkit/tsk/img/aff4.cpp")
        .file("../../vendor/sleuthkit/tsk/img/ewf.cpp")
        .file("../../vendor/sleuthkit/tsk/img/img_io.cpp")
        .file("../../vendor/sleuthkit/tsk/img/img_open.cpp")
        .file("../../vendor/sleuthkit/tsk/img/img_writer.cpp")
        .file("../../vendor/sleuthkit/tsk/img/logical_img.cpp")
        .file("../../vendor/sleuthkit/tsk/img/mult_files.cpp")
        .file("../../vendor/sleuthkit/tsk/img/qcow.cpp")
        .file("../../vendor/sleuthkit/tsk/img/raw.cpp")
        .file("../../vendor/sleuthkit/tsk/img/unsupported_types.cpp")
        .file("../../vendor/sleuthkit/tsk/img/vhd.cpp")
        .file("../../vendor/sleuthkit/tsk/img/vmdk.cpp")
        .file("../../vendor/sleuthkit/tsk/pool/apfs_pool_compat.cpp")
        .file("../../vendor/sleuthkit/tsk/pool/apfs_pool.cpp")
        .file("../../vendor/sleuthkit/tsk/pool/img_bfio_handle.cpp")
        .file("../../vendor/sleuthkit/tsk/pool/lvm_pool_compat.cpp")
        .file("../../vendor/sleuthkit/tsk/pool/lvm_pool.cpp")
        .file("../../vendor/sleuthkit/tsk/pool/pool_open.cpp")
        .file("../../vendor/sleuthkit/tsk/pool/pool_read.cpp")
        .file("../../vendor/sleuthkit/tsk/pool/pool_types.cpp")
        .file("../../vendor/sleuthkit/tsk/util/Bitlocker/BitlockerParser.cpp")
        .file("../../vendor/sleuthkit/tsk/util/Bitlocker/BitlockerUtils.cpp")
        .file("../../vendor/sleuthkit/tsk/util/Bitlocker/DataTypes.cpp")
        .file("../../vendor/sleuthkit/tsk/util/Bitlocker/MetadataEntry.cpp")
        .file("../../vendor/sleuthkit/tsk/util/Bitlocker/MetadataUtils.cpp")
        .file("../../vendor/sleuthkit/tsk/util/Bitlocker/MetadataValueAesCcmEncryptedKey.cpp")
        .file("../../vendor/sleuthkit/tsk/util/Bitlocker/MetadataValueKey.cpp")
        .file("../../vendor/sleuthkit/tsk/util/Bitlocker/MetadataValueOffsetAndSize.cpp")
        .file("../../vendor/sleuthkit/tsk/util/Bitlocker/MetadataValueStretchKey.cpp")
        .file("../../vendor/sleuthkit/tsk/util/Bitlocker/MetadataValueUnicode.cpp")
        .file("../../vendor/sleuthkit/tsk/util/Bitlocker/MetadataValueVolumeMasterKey.cpp")
        .file("../../vendor/sleuthkit/tsk/util/crypto.cpp")
        .file("../../vendor/sleuthkit/tsk/util/crypto.cpp")
        .file("../../vendor/sleuthkit/tsk/util/file_system_utils.cpp")
        .file("../../vendor/sleuthkit/tsk/util/file_system_utils.cpp");
    cfg_cc.compile("tsk_cc");
}
